# Generated by Django 5.2.9 on 2025-12-22 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_pricinglog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricinglog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
