# Generated by Django 5.2.9 on 2025-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketdata",
            name="recorded_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
