# Generated by Django 5.2.10 on 2026-01-20 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_transaction_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="客户编码"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="客户名称")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("retail", "零售客户"),
                            ("wholesale", "批发客户"),
                            ("distributor", "经销商"),
                            ("enterprise", "企业客户"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="客户类型",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="区域"
                    ),
                ),
                (
                    "credit_level",
                    models.IntegerField(default=3, verbose_name="信用等级"),
                ),
                (
                    "payment_terms",
                    models.IntegerField(default=30, verbose_name="账期(天)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["customer_code"],
            },
        ),
        migrations.CreateModel(
            name="ForecastConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="配置名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "service_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.95,
                        max_digits=4,
                        verbose_name="服务水平",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(default=7, verbose_name="提前期(天)"),
                ),
                (
                    "review_period_days",
                    models.IntegerField(default=30, verbose_name="检查周期(天)"),
                ),
                (
                    "categories",
                    models.JSONField(blank=True, default=list, verbose_name="适用品类"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "预测配置",
                "verbose_name_plural": "预测配置",
            },
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="预测日期")),
                ("target_month", models.IntegerField(verbose_name="目标月份")),
                ("target_year", models.IntegerField(verbose_name="目标年份")),
                (
                    "user_forecast",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="用户预测"
                    ),
                ),
                (
                    "predicted_actual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="预测实际"
                    ),
                ),
                (
                    "confidence_lower",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="置信下限"
                    ),
                ),
                (
                    "confidence_upper",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="置信上限"
                    ),
                ),
                (
                    "bias_rate",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=6, verbose_name="偏差率"
                    ),
                ),
                (
                    "mape",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=8, verbose_name="MAPE"
                    ),
                ),
                (
                    "mae",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="MAE"
                    ),
                ),
                (
                    "historical_records",
                    models.IntegerField(default=0, verbose_name="历史记录数"),
                ),
                (
                    "seasonal_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="季节因子",
                    ),
                ),
                (
                    "reliability",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=10,
                        verbose_name="可靠性",
                    ),
                ),
                (
                    "warning",
                    models.TextField(blank=True, null=True, verbose_name="警告信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="forecasting.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="inventory.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求预测",
                "verbose_name_plural": "需求预测",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="安全库存"
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="再订货点"
                    ),
                ),
                (
                    "target_stock_level",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="目标库存"
                    ),
                ),
                (
                    "lead_time_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="提前期需求"
                    ),
                ),
                (
                    "z_score",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="Z值"
                    ),
                ),
                (
                    "daily_demand",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="日均需求"
                    ),
                ),
                (
                    "daily_std_dev",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="日需求标准差"
                    ),
                ),
                (
                    "service_level",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="服务水平"
                    ),
                ),
                ("lead_time_days", models.IntegerField(verbose_name="提前期(天)")),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="计算时间"),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="计算人",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="forecasting.forecastconfig",
                        verbose_name="配置",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="forecasting.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="inventory.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存策略",
                "verbose_name_plural": "库存策略",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="DemandHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "week",
                    models.IntegerField(blank=True, null=True, verbose_name="周数"),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="实际数量"
                    ),
                ),
                (
                    "forecast_qty",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="预测数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="单价"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="品类"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_history",
                        to="forecasting.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_history",
                        to="inventory.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求历史",
                "verbose_name_plural": "需求历史",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="forecasting_product_cff1bc_idx",
                    ),
                    models.Index(
                        fields=["customer", "date"],
                        name="forecasting_custome_e52c61_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="forecasting_year_2544af_idx"
                    ),
                ],
            },
        ),
    ]
